schema = 1

[defaults]
user = "rderose"

[users.rderose]
username = "rderose"
full_name = "Robert DeRose"
email = "rderose@checkpt.com"
github = "RobertDeRose"

[users.DeRoseR]
username = "DeRoseR"
allow_nonportable = true
full_name = "Robert DeRose"
email = "rderose@checkpt.com"
github = "RobertDeRose"

[hosts.USMBDEROSER]
system = "aarch64-darwin"
user = "DeRoseR"
profiles = ["base", "dev", "mac"]

[hosts.USMBDEROSER.features]
personal_cache = true

[hosts.dev-som]
system = "aarch64-linux"
user = "rderose"
profiles = ["base", "dev", "linux"]

[hosts.dev-som.features]
personal_cache = true
