# schema
[settings]
experimental = true
env_shell_expand = true

[tools]
usage = "latest"
python = "latest"
hk = "latest"
actionlint = "latest"
jq = "latest"
pkl = "latest"
shellcheck = "latest"
shfmt = "latest"
tombi = "latest"
"aqua:Mic92/nixfmt-rs" = "latest"
"github:rust-lang/mdbook" = "latest"
"github:peterldowns/nix-search-cli" = "latest"

[env]
HK_MISE = 1

[hooks]
postinstall = "command -v hk >/dev/null && hk install --mise || true"

[task_config]
includes = [".mise/tasks"]
