"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
command_timeout = 750
continuation_prompt = "[│ ](fg:overlay0)"
format = """
[╭─](fg:overlay0)\
[](fg:surface0)\
$os\
$username\
$hostname\
[](fg:surface0 bg:surface1)\
$directory\
$git_branch\
$git_status\
$nix_shell\
$package\
$c\
$golang\
$nodejs\
$python\
$rust\
[](fg:surface1 bg:surface2)\
$cmd_duration\
$time\
$jobs\
[ ](bg:surface2)\
[](fg:surface2)
[╰─](fg:overlay0)$character"""
palette = "catppuccin_macchiato"
right_format = ""
scan_timeout = 30

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[os]
disabled = false
format = "[ $symbol](fg:mauve bg:surface0)"

[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = ""
CentOS = ""
Debian = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = ""
Gentoo = ""
Linux = ""
Macos = ""
Manjaro = ""
Mariner = ""
Mint = ""
NetBSD = ""
NixOS = ""
OpenBSD = ""
OpenCloudOS = ""
openEuler = ""
openSUSE = ""
OracleLinux = "⊂⊃"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
Solus = ""
SUSE = ""
Ubuntu = ""
Unknown = ""
Windows = ""

[username]
format = "[ $user](fg:text bg:surface0)"
show_always = true

[hostname]
format = "[@$hostname ](fg:sapphire bg:surface0)"
ssh_only = true
trim_at = "."

[directory]
format = "[ ](fg:blue bg:surface1)[ $path](fg:text bg:surface1)[$read_only](fg:red bg:surface1)"
home_symbol = "~"
read_only = " "
read_only_style = ""
truncate_to_repo = false
truncation_length = 4
truncation_symbol = "…/"

[git_branch]
format = "[ ](fg:green bg:surface1)[ $branch](fg:text bg:surface1)"
symbol = ""
truncation_length = 36
truncation_symbol = "…"

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
conflicted = "=${count}"
deleted = "×${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
format = "[ $all_status$ahead_behind](fg:yellow bg:surface1)"
modified = "!${count}"
renamed = "»${count}"
staged = "+${count}"
stashed = "≡${count}"
untracked = "?${count}"
up_to_date = ""

[nix_shell]
format = "[ $symbol](fg:mauve bg:surface1)[ $state( $name)](fg:subtext1 bg:surface1)"
heuristic = true
impure_msg = "impure"
pure_msg = "pure"
symbol = ""
unknown_msg = "shell"

[package]
format = "[ $symbol](fg:pink bg:surface1)[ $version](fg:subtext1 bg:surface1)"
symbol = "󰏗"

[c]
format = "[ $symbol](fg:sapphire bg:surface1)[ $version](fg:subtext1 bg:surface1)"
symbol = ""

[golang]
format = "[ $symbol](fg:sky bg:surface1)[ $version](fg:subtext1 bg:surface1)"
symbol = ""

[nodejs]
format = "[ $symbol](fg:green bg:surface1)[ $version](fg:subtext1 bg:surface1)"
symbol = ""

[python]
format = "[ $symbol](fg:yellow bg:surface1)[ ${pyenv_prefix}${version}( $virtualenv)](fg:subtext1 bg:surface1)"
symbol = ""

[rust]
format = "[ $symbol](fg:peach bg:surface1)[ $version](fg:subtext1 bg:surface1)"
symbol = ""

[cmd_duration]
format = "[ 󱎫](fg:peach bg:surface2)[ $duration](fg:subtext1 bg:surface2)"
min_time = 1000
show_milliseconds = false

[time]
disabled = false
format = "[ ](fg:rosewater bg:surface2)[ $time](fg:text bg:surface2)"
time_format = "%H:%M"

[jobs]
format = "[ ](fg:lavender bg:surface2)[ $number](fg:subtext1 bg:surface2)"
number_threshold = 1
symbol = ""
symbol_threshold = 1

[character]
error_symbol = '[\$](bold red)'
format = "$symbol "
success_symbol = '[\$](bold green)'
vimcmd_replace_one_symbol = "[❮](bold peach)"
vimcmd_replace_symbol = "[❮](bold peach)"
vimcmd_symbol = "[❮](bold lavender)"
vimcmd_visual_symbol = "[❮](bold yellow)"
