"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
command_timeout = 750
continuation_prompt = "[│ ](fg:overlay0)"
format = """
[╭─](fg:overlay0)$os$username$hostname$directory$git_branch$git_status$nix_shell$package$c$golang$nodejs$python$rust$cmd_duration$shell$time$status$jobs
[╰─](fg:overlay0)$character"""
palette = "catppuccin_macchiato"
right_format = ""
scan_timeout = 30

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[os]
disabled = false
format = "[](fg:blue)[$symbol](fg:base bg:blue)[](fg:blue) "

[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = ""
CentOS = ""
Debian = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = ""
Gentoo = ""
Linux = ""
Macos = ""
Manjaro = ""
Mariner = ""
Mint = ""
NetBSD = ""
NixOS = ""
OpenBSD = ""
OpenCloudOS = ""
openEuler = ""
openSUSE = ""
OracleLinux = "⊂⊃"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
Solus = ""
SUSE = ""
Ubuntu = ""
Unknown = ""
Windows = ""

[username]
format = "[](fg:mauve)[](fg:base bg:mauve)[](fg:mauve bg:surface0)[ $user](fg:text bg:surface0)[](fg:surface0) "
show_always = true

[hostname]
format = "[](fg:sapphire)[󰒋](fg:base bg:sapphire)[](fg:sapphire bg:surface0)[ $hostname](fg:text bg:surface0)[](fg:surface0) "
ssh_only = true
trim_at = "."

[directory]
format = "[](fg:blue)[](fg:base bg:blue)[](fg:blue bg:surface0)[ $path](fg:text bg:surface0)[$read_only](fg:red bg:surface0)[](fg:surface0) "
home_symbol = "~"
read_only = " "
read_only_style = ""
truncate_to_repo = false
truncation_length = 4
truncation_symbol = "…/"

[git_branch]
format = "[](fg:green)[](fg:base bg:green)[](fg:green bg:surface0)[ $branch](fg:text bg:surface0)[](fg:surface0) "
symbol = ""
truncation_length = 36
truncation_symbol = "…"

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
conflicted = "=${count}"
deleted = "×${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
format = "[](fg:yellow)[](fg:base bg:yellow)[](fg:yellow bg:surface0)[ $all_status$ahead_behind](fg:text bg:surface0)[](fg:surface0) "
modified = "!${count}"
renamed = "»${count}"
staged = "+${count}"
stashed = "≡${count}"
untracked = "?${count}"
up_to_date = ""

[nix_shell]
format = "[](fg:mauve)[$symbol](fg:base bg:mauve)[](fg:mauve bg:surface0)[ $state( $name)](fg:text bg:surface0)[](fg:surface0) "
heuristic = true
impure_msg = "impure"
pure_msg = "pure"
symbol = ""
unknown_msg = "shell"

[package]
format = "[](fg:pink)[$symbol](fg:base bg:pink)[](fg:pink bg:surface0)[ $version](fg:text bg:surface0)[](fg:surface0) "
symbol = "󰏗"

[c]
format = "[](fg:sapphire)[$symbol](fg:base bg:sapphire)[](fg:sapphire bg:surface0)[ $version](fg:text bg:surface0)[](fg:surface0) "
symbol = ""

[golang]
format = "[](fg:sky)[$symbol](fg:base bg:sky)[](fg:sky bg:surface0)[ $version](fg:text bg:surface0)[](fg:surface0) "
symbol = ""

[nodejs]
format = "[](fg:green)[$symbol](fg:base bg:green)[](fg:green bg:surface0)[ $version](fg:text bg:surface0)[](fg:surface0) "
symbol = ""

[python]
format = "[](fg:yellow)[$symbol](fg:base bg:yellow)[](fg:yellow bg:surface0)[ ${pyenv_prefix}${version}( $virtualenv)](fg:text bg:surface0)[](fg:surface0) "
symbol = ""

[rust]
format = "[](fg:peach)[$symbol](fg:base bg:peach)[](fg:peach bg:surface0)[ $version](fg:text bg:surface0)[](fg:surface0) "
symbol = ""

[cmd_duration]
format = "[](fg:peach)[󱎫](fg:base bg:peach)[](fg:peach bg:surface0)[ $duration](fg:text bg:surface0)[](fg:surface0) "
min_time = 1000
show_milliseconds = false


[shell]
bash_indicator = "bash"
disabled = false
fish_indicator = "fish"
format = "[](fg:teal)[](fg:base bg:teal)[](fg:teal bg:surface0)[ $indicator](fg:text bg:surface0)[](fg:surface0) "
ion_indicator = "ion"
powershell_indicator = "pwsh"
unknown_indicator = "shell"
xonsh_indicator = "xonsh"
zsh_indicator = "zsh"

[time]
disabled = false
format = "[](fg:rosewater)[](fg:base bg:rosewater)[](fg:rosewater bg:surface0)[ $time](fg:text bg:surface0)[](fg:surface0) "
time_format = "%H:%M"

[status]
disabled = false
format = "[](fg:red)[$symbol](fg:base bg:red)[](fg:red bg:surface0)[ $status](fg:text bg:surface0)[](fg:surface0) "
map_symbol = true
not_executable_symbol = ""
not_found_symbol = ""
recognize_signal_code = true
sigint_symbol = "󰜺"
signal_symbol = ""
symbol = ""

[jobs]
format = "[](fg:lavender)[$symbol](fg:base bg:lavender)[](fg:lavender bg:surface0)[ $number](fg:text bg:surface0)[](fg:surface0) "
number_threshold = 1
symbol = ""
symbol_threshold = 1

[character]
error_symbol = "[❯](bold red)"
format = "$symbol "
success_symbol = "[❯](bold green)"
vimcmd_replace_one_symbol = "[❮](bold peach)"
vimcmd_replace_symbol = "[❮](bold peach)"
vimcmd_symbol = "[❮](bold lavender)"
vimcmd_visual_symbol = "[❮](bold yellow)"
