alias ls='eza'
alias less='bat'
alias cat='bat'
alias oc='opencode'

alias gst='git status'
alias gd='git diff'
alias ga='git add'
alias gc='git commit --verbose'
alias 'gc!'='git commit --verbose --amend'
alias gco='git checkout'
alias gdca='git diff --cached'
alias gbD='git branch --delete --force'
alias gbd='git branch --delete'

alias ..='up 1'
alias ...='up 2'
alias ....='up 3'
alias .....='up 4'
