# templates/nixos/default.nix
# Host template for a Linux / NixOS machine.
# Copy this directory to hosts/x86_64-nixos/<hostname>/ to register a new host.
# easy-hosts sets networking.hostName automatically from the directory name.
{
  fullname,
  username,
  pkgs,
  ...
}: {
  users.users."${username}" = {
    isNormalUser = true;
    description  = fullname;
    home         = "/home/${username}";
    shell        = pkgs.zsh;
    extraGroups  = [ "wheel" "networkmanager" "docker" ];
    # Add your SSH public key here:
    # openssh.authorizedKeys.keys = [ "ssh-ed25519 AAAA..." ];
  };

  # Import the hardware config generated by: sudo nixos-generate-config
  # The nix:add-host task copies this file automatically on NixOS machines.
  # To add a nixos-hardware module, append it here, e.g.:
  #   ./hardware-configuration.nix
  #   nixos-hardware.nixosModules.lenovo-thinkpad-x1-carbon-gen11
  imports = [ ./hardware-configuration.nix ];
}
