#!/usr/bin/env bash
# [MISE] description="Open a nix repl with nixpkgs"
# [MISE] quiet=true

set -euo pipefail

TASK_FILE="${BASH_SOURCE[0]}"
REPO_ROOT="$(git -C "$(dirname "$TASK_FILE")" rev-parse --show-toplevel)"
cd "$REPO_ROOT"

nix repl --expr 'import (builtins.getFlake "nixpkgs") {}'
